name: release

on:
  push:
    branches:
      - main
      - next

permissions:
  contents: release
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - run: npm i -g pnpm
      - run: pnpm ci
      - run: pnpm build
      - run: pnpm audit signature
      - name: release
        env:
          npm_token: ${{ secrets.npm_token }}
        run: pnpx semantic-release
